# Generated by Django 4.2.4 on 2023-08-08 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sql", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataentry",
            old_name="content",
            new_name="sql_statement",
        ),
    ]
